### ISSUE TITLE
Icon should NOT be the same for both send/receive 

### ISSUE THREAD

**Issue by Janaka-Steph** [tdex-network/tdex-app#451]
![8A59A006-E300-4A5B-805D-73AF326F94FA](https://user-images.githubusercontent.com/4022128/144855347-598da816-f23a-47b5-8ace-6eef717f41b3.jpg)

**Comment by CL-Seven** [comment]
Hello 

it Should be different probably a misnaming of the issue?  

	EMPOWERING  PIONEERS

Claudio Levrini
CEO & CO-FOUNDER
***@***.*** - @CLCH123 - sevenlabs.io
This e-mail is intended only for the recipients named above. It may contain confidential or privileged information and should not be read, copied or otherwise used by another person. If you received this in error please contact SevelLabs and delete the e-mail from your system. Please consider the environment before printing this e-mail.

**Comment by Janaka-Steph** [comment]
@FilippoSeven

**Comment by tiero** [comment]
Yes the icon should be inverted (now the same with the horizontal line on the bottom)
